# ----------------------- #
# QC pipeline DendrouLab
# ----------------------- #
# written by Charlotte Rich-Griffin, Thom Tomas, Fabiola Curion
# maintained by Charlotte Rich-Griffin

# needs a sample metadata file (see resources for an example)
# will run :
#   summary plots of 10x metrics
#   scrublet scores
#   scanpy QC
#   summary QC plots

# Followed by integration pipeline and clustering pipeline. This pipeline does not perform any filtering,
# this happens as the first stpe in the integration pipeline. See pipeline_integration.yml for details

# Note that if you are combining mutliple datasets from different source the final anndata object will only contain the intersect of the genes
# from all the data sets. For example if the mitochondrial genes have been excluded from one of the inputs, they will be excluded from the final data set.
# In this case it might be wise to run qc separately on each dataset, and them merge them together to create on h5ad file to use as input for
# integration pipeline.

project: alt_start
sample_prefix: alt_start

# submission_file format:
# For qc_cellranger the required columns are
# sample_id  |     raw_path   |     filtered_path
# Example at resources/sample_file_cellranger.txt
#
# For qc_general the required columns are
# sample_id       path        type
# Example at resources/sample_file_general.txt
submission_file: ../data/qc_alt_sample_caf.txt
metadatacols: filetype,library_id

# if set to True then the submission file must have a "demultiplex_map_file" column
# The demultiplex map file must have one column called barcode_id and one column called antibody
# a second demultiplex metdata file path can also be included in submission file
# (column names: demultiplex_map_file demultiplex_mtd_file)
# specify which columns you want to keep from the demultplex mtd file in metadatacols
demultiplex:
  include: True # True or False
  metadatacols: antibody,sample_name,sex,multiplex_run

# compute resource options
# ------------------------
resources:
  # Number of threads used for parallel jobs
  # high = make anndata
  threads_high: 2
  # medium = running scrublet per sample
  threads_medium: 1
  # low = plotting
  threads_low: 1


## scrublet
# ------------
scr:
  # The values here are the default values, if you were to leave a paramter pblank, it would default to these value,
  expected_doublet_rate: 0.06
  #the expected fraction of transcriptomes that are doublets, typically 0.05-0.1.
  # Results are not particularly sensitive to this parameter")
  sim_doublet_ratio: 2
  # the number of doublets to simulate, relative to the number of observed transcriptomes.
  # Setting too high is computationally expensive. Min tested 0.5
  n_neighbours: 20
  # Number of neighbors used to construct the KNN classifier of observed transcriptomes
  # and simulated doublets.
  # The default value of round(0.5*sqrt(n_cells)) generally works well.

  min_counts: 2
  # Used for gene filtering prior to PCA. Genes expressed at fewer than `min_counts` in fewer than `min_cells` (see below) are excluded"
  min_cells: 3
  # Used for gene filtering prior to PCA.
  # Genes expressed at fewer than `min_counts` (see above) in fewer than `min_cells` are excluded.")
  min_gene_variability_pctl: 85
  # Used for gene filtering prior to PCA. Keep the most highly variable genes
    # (in the top min_gene_variability_pctl percentile),
    #as measured by the v-statistic [Klein et al., Cell 2015]")
  n_prin_comps: 30
  # Number of principal components used to embed the transcriptomes
  # prior to k-nearest-neighbor graph construction
  use_thr: True
  # use a user defined thr to define min doublet score to split true from false doublets?
  # if false just use what the software produces
  # this threshold applies to plots, a=no actual fitlering takes place.
  call_doublets_thr: 0.25
  #if use_thr is True, this thr will be used to define doublets


# ------------
## scanpy QC
# ------------

# options are blank for don't run, "default" (the data stored within the package),
# or paths to your own datasets
# cc genes will plot the proportions of cell cycle genes, iggenes will plot the proportion of iggenes (recommended to leave as default)
ccgenes: default
iggenesfile: default

# ------------
## plotQC
# ------------
plotqc:
  # likely a combination of metadatacolumns and demultiplex_metadatacols
  grouping_var: sample_id,antibody,sex
  metrics: pct_counts_mt,pct_counts_rp,pct_counts_hb,pct_counts_ig,doublet_scores

